GET http://localhost:8888   HTTP/1.1
content-type: application/json

###
POST  http://localhost:8888   HTTP/1.1
content-type: application/json

{
    "name":"Hendry",
    "salary":"61888",
    "age":"26"
}